UPDATE breed_comments SET comment_en = 'Mixed breeds are known for their strong immune systems and unique personalities! Every mix is one-of-a-kind. Regular checkups help keep that unique charm going strong!' WHERE id = 1;
UPDATE breed_comments SET comment_en = 'Fun fact: mixed breed dogs often live longer than purebreds thanks to genetic diversity! A balanced diet helps them thrive even more.' WHERE id = 2;
UPDATE breed_comments SET comment_en = 'Maltese have been companion dogs for over 2,000 years. True royalty! Watch out for tear stains and dental care though.' WHERE id = 3;
UPDATE breed_comments SET comment_en = 'Despite their tiny size, Maltese are surprisingly brave and full of energy! Their delicate joints need proper nutrition to stay strong.' WHERE id = 4;
UPDATE breed_comments SET comment_en = 'Poodles rank as one of the smartest dog breeds in the world! Big brains in a fluffy package. Keep those ears clean and dry to avoid infections.' WHERE id = 5;
UPDATE breed_comments SET comment_en = 'Poodles are hypoallergenic and barely shed. Great for allergy-prone families! Regular grooming and skin-friendly nutrition are a must.' WHERE id = 6;
UPDATE breed_comments SET comment_en = 'Shih Tzus were originally bred for Chinese royalty. They are natural lap warmers! Those big beautiful eyes need extra care to stay healthy.' WHERE id = 7;
UPDATE breed_comments SET comment_en = 'Shih Tzu means "little lion," but they are all about cuddles, not roaring! Watch their breathing in hot weather and keep them cool.' WHERE id = 8;
UPDATE breed_comments SET comment_en = 'Pomeranians descended from large sled dogs. Tiny body, big dog attitude! Their teeth need extra attention since small breeds are prone to dental issues.' WHERE id = 9;
UPDATE breed_comments SET comment_en = 'Queen Victoria owned a Pomeranian, making them a worldwide sensation! That gorgeous double coat needs regular brushing and good nutrition.' WHERE id = 10;
UPDATE breed_comments SET comment_en = 'Chihuahuas are the smallest breed but have the biggest personalities! Fearless little warriors. Keep an eye on their dental health and blood sugar.' WHERE id = 11;
UPDATE breed_comments SET comment_en = 'Chihuahuas love to burrow under blankets. Tiny heat-seekers! Small meals throughout the day help keep their energy steady.' WHERE id = 12;
UPDATE breed_comments SET comment_en = 'Bichon Frises are natural entertainers. They were literally circus performers! Their sensitive skin needs gentle care and the right diet.' WHERE id = 13;
UPDATE breed_comments SET comment_en = 'That cloud-like coat is hypoallergenic! Bichons are great for sensitive owners. Watch for tear stains and keep up with grooming.' WHERE id = 14;
UPDATE breed_comments SET comment_en = 'Yorkies were originally bred to catch rats in textile mills. Tiny but mighty hunters! Their small stomachs need nutrient-rich meals.' WHERE id = 15;
UPDATE breed_comments SET comment_en = 'A Yorkie''s silky coat is more like human hair than fur. It just keeps growing! Good nutrition keeps that coat shiny and healthy.' WHERE id = 16;
UPDATE breed_comments SET comment_en = 'Dachshunds were bred to hunt badgers. That long body was made for tunneling! Keeping them at a healthy weight is key to protecting their back.' WHERE id = 17;
UPDATE breed_comments SET comment_en = 'The famous "hot dog" name actually came from Dachshunds, not the other way around! Watch their weight closely since extra pounds put stress on their spine.' WHERE id = 18;
UPDATE breed_comments SET comment_en = 'Corgis are the Queen of England''s favorite breed. True royal pups! Those short legs carry a lot of body, so weight management is important.' WHERE id = 19;
UPDATE breed_comments SET comment_en = 'Despite those short legs, Corgis are herding dogs. Fast, agile, and full of stamina! Joint-friendly nutrition helps keep them active for years.' WHERE id = 20;
UPDATE breed_comments SET comment_en = 'Beagles have about 220 million scent receptors. Their nose knows everything! Keep an eye on their weight though. Beagles love to eat!' WHERE id = 21;
UPDATE breed_comments SET comment_en = 'Snoopy is a Beagle! One of the most beloved cartoon dogs of all time. Those floppy ears need regular cleaning to prevent infections.' WHERE id = 22;
UPDATE breed_comments SET comment_en = 'Golden Retrievers are the ultimate family dogs. Gentle, loyal, and always smiling! Skin and coat care is important for this breed.' WHERE id = 23;
UPDATE breed_comments SET comment_en = 'Goldens are top picks for therapy and guide dogs thanks to their incredible empathy. Keep their joints healthy with the right nutrition as they age.' WHERE id = 24;
UPDATE breed_comments SET comment_en = 'Labradors have been the #1 most popular dog breed in America for over 30 years! They gain weight easily though, so portion control matters.' WHERE id = 25;
UPDATE breed_comments SET comment_en = 'Labs have webbed toes. They are natural-born swimmers! Joint support is key since larger breeds can develop hip issues over time.' WHERE id = 26;
UPDATE breed_comments SET comment_en = 'Border Collies are considered THE smartest dog breed. They can learn a new command in under 5 seconds! All that energy means they need top-notch fuel.' WHERE id = 27;
UPDATE breed_comments SET comment_en = 'A Border Collie named Chaser learned over 1,000 words. The most of any dog ever recorded! Keep their eyes checked regularly for this breed.' WHERE id = 28;
UPDATE breed_comments SET comment_en = 'Huskies can run over 100 miles a day in sub-zero temperatures. Ultimate endurance athletes! That thick double coat needs proper nutrition to stay healthy.' WHERE id = 29;
UPDATE breed_comments SET comment_en = 'Huskies are famous for their dramatic "talking." They howl, whine, and argue like no other breed! Keep those striking eyes checked regularly.' WHERE id = 30;
UPDATE breed_comments SET comment_en = 'Jindos are legendary for their loyalty. One Jindo walked 180 miles to return to its owner! Plenty of exercise and a solid diet keep them happy.' WHERE id = 31;
UPDATE breed_comments SET comment_en = 'The Jindo is a Korean national treasure. Officially designated Natural Monument #53! Their active nature means they need high-quality nutrition.' WHERE id = 32;
UPDATE breed_comments SET comment_en = 'Sapsalis were believed to ward off evil spirits in Korean folklore. Fluffy guardian angels! That long coat needs regular grooming and skin care.' WHERE id = 33;
UPDATE breed_comments SET comment_en = 'The Sapsali nearly went extinct but was saved by dedicated Korean breeders in the 1980s! A healthy diet keeps their signature fluffy coat in top shape.' WHERE id = 34;
UPDATE breed_comments SET comment_en = 'Every dog is special! Let''s find the perfect nutrition for your unique pup. The right food makes all the difference!' WHERE id = 35;
UPDATE breed_comments SET comment_en = 'No matter the breed, proper nutrition is the foundation of a happy, healthy life! Let''s find what works best.' WHERE id = 36;
UPDATE breed_comments SET comment_en = 'Mixed breed cats are wonderfully unique. No two are ever the same! A well-balanced diet helps them stay healthy for years to come.' WHERE id = 37;
UPDATE breed_comments SET comment_en = 'Mixed cats tend to be healthier thanks to genetic diversity. Nature''s best design! Regular vet visits keep that advantage going strong.' WHERE id = 38;
UPDATE breed_comments SET comment_en = 'Korean Shorthairs are the most popular cats in Korea. Adaptable, smart, and low-maintenance! Watch their weight since they love a good meal.' WHERE id = 39;
UPDATE breed_comments SET comment_en = 'Korean Shorthairs are excellent hunters with strong, athletic builds! Keep them active and well-fed to maintain that natural athleticism.' WHERE id = 40;
UPDATE breed_comments SET comment_en = 'Persians are one of the oldest cat breeds. They''ve been adored for thousands of years! Those flat faces need extra eye and breathing care.' WHERE id = 41;
UPDATE breed_comments SET comment_en = 'Persians are the ultimate couch companions. Calm, gentle, and endlessly fluffy! Daily grooming and hairball-friendly food are a must.' WHERE id = 42;
UPDATE breed_comments SET comment_en = 'Maine Coons are the largest domestic cat breed. Some weigh over 25 pounds! Heart health and joint care are important for these gentle giants.' WHERE id = 43;
UPDATE breed_comments SET comment_en = 'Maine Coons love water and are known to play in their water bowls. Unusual for cats! Their large frame needs proper nutrition to support those joints.' WHERE id = 44;
UPDATE breed_comments SET comment_en = 'British Shorthairs are the teddy bears of the cat world. Round face, chunky body, pure charm! They tend to gain weight, so watch those portions.' WHERE id = 45;
UPDATE breed_comments SET comment_en = 'The Cheshire Cat from Alice in Wonderland was inspired by a British Shorthair! Heart health checkups are a good idea for this breed.' WHERE id = 46;
UPDATE breed_comments SET comment_en = 'Scottish Folds get their unique folded ears from a natural genetic mutation. Adorably owl-like! Their joints need extra TLC, so proper nutrition is key.' WHERE id = 47;
UPDATE breed_comments SET comment_en = 'Scottish Folds are famous for sitting in quirky "Buddha" poses. They are natural comedians! Joint-friendly food helps keep them comfortable and mobile.' WHERE id = 48;
UPDATE breed_comments SET comment_en = 'Russian Blues have a unique double coat that shimmers silver in the light. Living velvet! They can be picky eaters, so finding the right food matters.' WHERE id = 49;
UPDATE breed_comments SET comment_en = 'Russian Blues are known for their "smile." The shape of their mouth makes them look permanently happy! Watch their weight since they enjoy snacking.' WHERE id = 50;
UPDATE breed_comments SET comment_en = 'Siamese cats are one of the most vocal breeds. They will literally have conversations with you! Dental care is especially important for Siamese.' WHERE id = 51;
UPDATE breed_comments SET comment_en = 'Siamese kittens are born completely white. Their color points develop as they grow! A protein-rich diet helps keep their sleek body in top shape.' WHERE id = 52;
UPDATE breed_comments SET comment_en = 'Ragdolls go completely limp when you pick them up. That is literally how they got their name! Heart health is something to keep an eye on for this breed.' WHERE id = 53;
UPDATE breed_comments SET comment_en = 'Ragdolls are often called "puppy cats" because they follow their owners around the house! Urinary health support through diet is a smart move for them.' WHERE id = 54;
UPDATE breed_comments SET comment_en = 'Abyssinians are one of the oldest known cat breeds. They look like miniature mountain lions! Keep their teeth and gums healthy with the right nutrition.' WHERE id = 55;
UPDATE breed_comments SET comment_en = 'Abyssinians are incredibly active and curious. They love climbing to the highest spot in the room! All that energy means they need a nutrient-packed diet.' WHERE id = 56;
UPDATE breed_comments SET comment_en = 'Every cat is unique! Let''s find the purr-fect nutrition for your feline friend. The right food makes a real difference!' WHERE id = 57;
UPDATE breed_comments SET comment_en = 'No matter the breed, the right nutrition makes all the difference for a happy cat! Let''s find the best match.' WHERE id = 58;

SELECT id, breed, comment_en FROM breed_comments LIMIT 5;
